FROM python:3.8

WORKDIR /home/microservice

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

ENTRYPOINT ["/bin/bash", "/home/microservice/local-entrypoint.sh"]

CMD ["python", "-u", "/home/microservice/main.py"]
